name: Build Extension

on:
  workflow_dispatch:

  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g vsce

      - name: Build Extension
        run: vsce package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: dspf-edit-pr-build
          path: ./*.vsix
          if-no-files-found: error